on:
  workflow_dispatch: 

jobs:
  run-fishtest:
    strategy:
      fail-fast: false
      matrix:
        shard: [0,1,2,3,4,5,6,7,8]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          repository: official-stockfish/fishtest
      - name: Setup C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@v1.2
      - name: Setup Python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: 3.13
      - name: fishtest
        run: |
          cd worker/
          cat > fishtest.cfg <<'EOF'
          ${{ secrets.FISHTEST }}
          EOF
      
          python - <<'PY'
          import configparser
          import secrets
      
          cfg = configparser.ConfigParser()
          cfg.read("fishtest.cfg")
          cfg["private"]["hw_seed"] = str(secrets.randbits(64))
      
          with open("fishtest.cfg", "w") as f:
              cfg.write(f)
          PY
          python worker.py 
