name: fishtest

on:
  workflow_dispatch:
jobs:
  run-fishtest:
    strategy:
      fail-fast: false
      matrix:
        shard: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          repository: official-stockfish/fishtest
      - name: Setup C/C++ Compiler
        uses: rlalik/setup-cpp-compiler@v1.2
      - name: Setup Python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: 3.13
      - name: fishtest
        run: |
          cd worker/
          cat > fishtest.cfg <<'EOF'
          ${{ secrets.FISHTEST }}
          EOF
          # sufficient
          RAND_SUFFIX=$(openssl rand -hex 2)
          WORKER_NAME="beg${{ matrix.shard }}x${RAND_SUFFIX}"
          
          timeout --signal=SIGINT 21570s python worker.py -u "$WORKER_NAME" -c MAX
